# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

block_minority_prop_cpp <- function(house_block, resident_house, resident_minority, n_block) {
    .Call(`_addin_LiangSeg_block_minority_prop_cpp`, house_block, resident_house, resident_minority, n_block)
}

neib_ethnicity_prop <- function(neib_ind, house_minority) {
    .Call(`_addin_LiangSeg_neib_ethnicity_prop`, neib_ind, house_minority)
}

neib_SES_prop <- function(neib_ind, house_SES) {
    .Call(`_addin_LiangSeg_neib_SES_prop`, neib_ind, house_SES)
}

